# Generated by Django 2.2.1 on 2019-06-25 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDPE_Grade_Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Active_Status', models.BooleanField()),
                ('hdpe_Grade_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Grade_Number')),
                ('hdpe_Grade_Run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Grade_Run')),
            ],
        ),
    ]
