# Generated by Django 2.2.1 on 2019-06-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hdpe_grade_activation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hdpe_grade_activation',
            options={'verbose_name_plural': 'HDPE_Grade_Activation'},
        ),
    ]
