# Generated by Django 2.2.1 on 2019-06-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190625_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdpe_grade_run',
            name='Confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
