# Generated by Django 2.2.1 on 2019-06-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hdpe_grade_run_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdpe_execution_parameters',
            name='Start_Date_Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
