# Generated by Django 2.2.1 on 2019-06-29 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_hdpe_execution_parameters_start_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hdpe_transition',
            name='hdpe_Grade_Number_From_To',
        ),
        migrations.AddField(
            model_name='hdpe_transition',
            name='hdpe_Grade_Number_From',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hdpe_Grade_Number_From', to='api.HDPE_Grade_Number'),
        ),
        migrations.AddField(
            model_name='hdpe_transition',
            name='hdpe_Grade_Number_To',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hdpe_Grade_Number_To', to='api.HDPE_Grade_Number'),
        ),
    ]
