# Generated by Django 2.2.1 on 2019-06-29 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190629_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDPE_Output_Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.IntegerField()),
                ('Transition_Amount', models.FloatField()),
                ('hdpe_Output_Summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Output_Summary')),
                ('hdpe_Trains', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Trains')),
                ('hdpe_Transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Transition')),
            ],
            options={
                'verbose_name_plural': 'HDPE_Output_Summary',
            },
        ),
        migrations.CreateModel(
            name='HDPE_Output_NonPrime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.IntegerField()),
                ('NP_Production', models.FloatField()),
                ('OG_Production', models.FloatField()),
                ('LG_Production', models.FloatField()),
                ('Ethylene_Consumed', models.FloatField()),
                ('Propylene_Consumed', models.FloatField()),
                ('hdpe_Output_Summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Output_Summary')),
            ],
            options={
                'verbose_name_plural': 'HDPE_Output_Summary',
            },
        ),
        migrations.CreateModel(
            name='HDPE_Output_Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.IntegerField()),
                ('Production_Amount', models.FloatField()),
                ('hdpe_Grade_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Grade_Number')),
                ('hdpe_Output_Summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Output_Summary')),
                ('hdpe_Trains', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Trains')),
            ],
            options={
                'verbose_name_plural': 'HDPE_Output_Summary',
            },
        ),
    ]
