# Generated by Django 2.2.1 on 2019-06-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_hdpe_output_grade_hdpe_output_nonprime_hdpe_output_transition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hdpe_output_grade',
            options={'verbose_name_plural': 'HDPE_Output_Grade'},
        ),
        migrations.AlterModelOptions(
            name='hdpe_output_nonprime',
            options={'verbose_name_plural': 'HDPE_Output_NonPrime'},
        ),
        migrations.AlterModelOptions(
            name='hdpe_output_transition',
            options={'verbose_name_plural': 'HDPE_Output_Transition'},
        ),
    ]
