# Generated by Django 2.2.1 on 2019-06-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190629_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hdpe_last_maintenance',
            name='hdpe_Last_Running_Grades',
        ),
        migrations.RemoveField(
            model_name='hdpe_last_transition_grade',
            name='hdpe_Last_Running_Grades',
        ),
        migrations.RemoveField(
            model_name='hdpe_last_under_restart',
            name='hdpe_Last_Running_Grades',
        ),
        migrations.DeleteModel(
            name='HDPE_Last_Main_Grade',
        ),
        migrations.DeleteModel(
            name='HDPE_Last_Maintenance',
        ),
        migrations.DeleteModel(
            name='HDPE_Last_Transition_Grade',
        ),
        migrations.DeleteModel(
            name='HDPE_Last_Under_Restart',
        ),
    ]
