# Generated by Django 2.2.1 on 2019-06-29 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190629_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDPE_Last_Under_Restart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remaining_Hours_Max_TPH', models.FloatField()),
                ('hdpe_Grade_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Grade_Number')),
                ('hdpe_Last_Running_Grades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Last_Running_Grades')),
                ('hdpe_Trains', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Trains')),
            ],
            options={
                'verbose_name_plural': 'HDPE_Last_Under_Restart',
            },
        ),
        migrations.CreateModel(
            name='HDPE_Last_Transition_Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transition_Hours_Completed', models.FloatField()),
                ('hdpe_Last_Running_Grades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Last_Running_Grades')),
                ('hdpe_Trains', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Trains')),
                ('hdpe_Transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Transition')),
            ],
            options={
                'verbose_name_plural': 'HDPE_Last_Transition_Grade',
            },
        ),
        migrations.CreateModel(
            name='HDPE_Last_Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maintenance_Hours_Left', models.FloatField()),
                ('hdpe_Last_Running_Grades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Last_Running_Grades')),
                ('hdpe_Trains', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Trains')),
            ],
            options={
                'verbose_name_plural': 'HDPE_Last_Maintenance',
            },
        ),
        migrations.CreateModel(
            name='HDPE_Last_Main_Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade_Hours_Completed', models.FloatField()),
                ('Series_Parallel_Hours_Completed', models.FloatField()),
                ('Family_Hours_Completed', models.FloatField()),
                ('hdpe_Grade_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Grade_Number')),
                ('hdpe_Last_Running_Grades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Last_Running_Grades')),
                ('hdpe_Trains', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Trains')),
            ],
            options={
                'verbose_name_plural': 'HDPE_Last_Main_Grade',
            },
        ),
    ]
