# Generated by Django 2.2.1 on 2019-06-29 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_hdpe_last_main_grade_hdpe_last_maintenance_hdpe_last_transition_grade_hdpe_last_under_restart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdpe_last_maintenance',
            name='Maintenance_Hours_Left',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hdpe_last_maintenance',
            name='hdpe_Trains',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Trains'),
        ),
        migrations.AlterField(
            model_name='hdpe_last_transition_grade',
            name='Transition_Hours_Completed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hdpe_last_transition_grade',
            name='hdpe_Trains',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Trains'),
        ),
        migrations.AlterField(
            model_name='hdpe_last_transition_grade',
            name='hdpe_Transition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Transition'),
        ),
        migrations.AlterField(
            model_name='hdpe_last_under_restart',
            name='Remaining_Hours_Max_TPH',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hdpe_last_under_restart',
            name='hdpe_Grade_Number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Grade_Number'),
        ),
        migrations.AlterField(
            model_name='hdpe_last_under_restart',
            name='hdpe_Trains',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.HDPE_Trains'),
        ),
    ]
