# Generated by Django 2.2.1 on 2019-06-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_hdpe_grade_run_run_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdpe_grade_run',
            name='Run_Month',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hdpe_grade_run',
            name='Run_Year',
            field=models.TextField(blank=True, null=True),
        ),
    ]
